# Explore here

In [22]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/4GeeksAcademy/k-nearest-neighbors-project-tutorial/refs/heads/main/winequality-red.csv', sep=';')

df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

Tenemos escalas distintas pero no tampoco tanto, van en rangos bastantes cercanos, entre 0 y 100, otras entre 0 y 1. La escalas no están tan alejadas/diferentes, asique vamos a usar una estandarización. 

A nosotros nos pidieron predecir: MALO, MEDIO Y BUENO, y en la columna 'quality' (que está en numérico) hay valores más alto de 3.

Vamos a ver qué hay en 'quality':

In [23]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3])

y aquí nos muestra los números que hay en la columna que van del 3 al 8, cómo podemos dividir esos número en malo, medio y bueno? Tenemos que mapear esta columna:

In [24]:
df['quality'] = df['quality'].map({3:'bad', 4: 'bad', 5:'mid', 6: 'mid', 7:'good', 8:'good'})

Lo que hacemos con 'map' es aplicar una transformación a una columna. Tmb lo podemos hacer con una función y un for (opción más larga pero tmb correcta).

In [25]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,mid
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,mid
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,mid
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,mid
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,mid

In [26]:
# Bueno, hasta acá ya tenemos nuestro 'quality' categorizado, y tenemos que estandarizar nuestras variables objetivo, asique lo primero que tenemos que hacer es definir nuestras X e Y.

x= df.drop(columns=['quality'])
y= df['quality']

# Vamos a hacer nuestra división en entrenamiento y test:

from sklearn.model_selection import train_test_split

x_train, y_train, x_test, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

x_train.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
493,8.7,0.690,0.31,3.0,0.086,23.0,81.0,1.00020,3.48,0.74,11.6
354,6.1,0.210,0.40,1.4,0.066,40.5,165.0,0.99120,3.25,0.59,11.9
342,10.9,0.390,0.47,1.8,0.118,6.0,14.0,0.99820,3.30,0.75,9.8
834,8.8,0.685,0.26,1.6,0.088,16.0,23.0,0.99694,3.32,0.47,9.4
705,8.4,1.035,0.15,6.0,0.073,11.0,54.0,0.99900,3.37,0.49,9.9

In [ ]:
# Ahora estandarizamos:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_esc = scaler.fit_transform(x_train, y_train)
x_test_esc = scaler.transform (x_test) 

# Y luego los tengo que volver DataFrame:

x_train_esc = pd.DataFrame(x_train_esc, columns= x_train.columns, index= x_train.index)
x_test_esc = pd.DataFrame(x_test_esc, columns= x_test.columns, index= x_test.index)

x_train_esc.head()

/home/vscode/.local/lib/python3.11/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

ValueError: could not convert string to float: 'mid'